In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
%matplotlib inline

In [11]:
df = pd.read_csv('./data/ufc-master.csv')

In [12]:
df.shape

(4307, 113)

In [15]:
df.head()

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,B_Featherweight_rank,B_Bantamweight_rank,B_Flyweight_rank,B_Pound-for-Pound_rank,better_rank,finish,finish_details,finish_round,finish_round_time,total_fight_time_secs
0,Robert Whittaker,Darren Till,-130,107,76.923077,107.000000,7/25/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,Red,U-DEC,NaN,5.0,5:00,1500.0
1,Mauricio Rua,Rogerio Nogueira,-190,150,52.631579,150.000000,7/25/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,Red,S-DEC,NaN,3.0,5:00,900.0
2,Fabricio Werdum,Alexander Gustafsson,260,-335,260.000000,29.850746,7/25/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,Blue,SUB,Armbar,1.0,2:30,150.0
3,Carla Esparza,Marina Rodriguez,145,-182,145.000000,54.945055,7/25/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,Red,S-DEC,NaN,3.0,5:00,900.0
4,Paul Craig,Gadzhimurad Antigulov,-137,110,72.992701,110.000000,7/25/2020,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,NaN,neither,SUB,Triangle Choke,1.0,2:06,126.0

In [23]:
num_vars = df.select_dtypes(include=['float', 'int']).columns
cat_vars = df.select_dtypes(include=['object']).columns

In [30]:
df[num_vars].isna().sum()

R_ev                               0
B_ev                               0
B_avg_SIG_STR_landed             930
B_avg_SIG_STR_pct                765
B_avg_SUB_ATT                    832
B_avg_TD_landed                  833
B_avg_TD_pct                     842
B_Height_cms                       0
B_Reach_cms                        0
R_avg_SIG_STR_landed             455
R_avg_SIG_STR_pct                357
R_avg_SUB_ATT                    357
R_avg_TD_landed                  357
R_avg_TD_pct                     367
R_Height_cms                       0
R_Reach_cms                        0
height_dif                         0
reach_dif                          0
sig_str_dif                        0
avg_sub_att_dif                    0
avg_td_dif                         0
B_match_weightclass_rank        3551
R_match_weightclass_rank        3145
R_Women's Flyweight_rank        4271
R_Women's Featherweight_rank    4301
R_Women's Strawweight_rank      4216
R_Women's Bantamweight_rank     4203
R_Heavyweight_rank              4181
R_Light Heavyweight_rank        4184
R_Middleweight_rank             4193
R_Welterweight_rank             4180
R_Lightweight_rank              4184
R_Featherweight_rank            4184
R_Bantamweight_rank             4186
R_Flyweight_rank                4179
R_Pound-for-Pound_rank          4166
B_Women's Flyweight_rank        4281
B_Women's Featherweight_rank    4307
B_Women's Strawweight_rank      4255
B_Women's Bantamweight_rank     4237
B_Heavyweight_rank              4212
B_Light Heavyweight_rank        4226
B_Middleweight_rank             4221
B_Welterweight_rank             4228
B_Lightweight_rank              4228
B_Featherweight_rank            4226
B_Bantamweight_rank             4232
B_Flyweight_rank                4222
B_Pound-for-Pound_rank          4281
finish_round                     225
total_fight_time_secs            225
dtype: int64